### ISSUE TITLE
課程查詢功能: 新增最愛課程, 課程圖片

### ISSUE THREAD

**Issue by honor2016tw** [NTNU-SE-Alpha/backend#8]
### 實作細節
- 讓使用者能夠新增最愛課程
- 能儲存課程圖片

### 參考格式
```
[
    {
      id: 1,
      name: "軟體工程",
      teacher: "Mr. Chen",
      weekday: "Monday",
      semester: "2024 Spring",
      archive: false,
      isFavorite: false,
      image: "images/c1.png",
      order: 1
    },
    {
      id: 2,
      name: "資訊科技",
      teacher: "Mrs. Wang",
      weekday: "Wednesday",
      semester: "2024 Spring",
      archive: false,
      isFavorite: false,
      image: "images/c1.png",
      order: 2
    },
    {
      id: 3,
      name: "化學",
      teacher: "Mr. Li",
      weekday: "Friday",
      semester: "2024 Fall",
      archive: true,
      isFavorite: false,
      image: "images/loginbg.png",
      order: 3
    },
    {
      id: 4,
      name: "生物",
      teacher: "Mrs. Chang",
      weekday: "Tuesday",
      semester: "2024 Fall",
      archive: true,
      isFavorite: false,
      image: "images/c1.png",
      order: 4
    },
    {
      id: 5,
      name: "數學",
      teacher: "Mr. Zhang",
      weekday: "Thursday",
      semester: "2024 Spring",
      archive: false,
      isFavorite: false,
      image: "images/c2.png",
      order: 5
    }
  ]
```

**Comment by edison0828** [comment]
❯ python init_db.py
保存目錄路徑: /Users/edisonlin/Documents/git-repos/軟工專案/backend/AI/saved_data
Traceback (most recent call last):
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3302, in raw_connection
    return self.pool.connect()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 621, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/pymysql/connections.py", line 979, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/pymysql/_auth.py", line 241, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'sys'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/edisonlin/Documents/git-repos/軟工專案/backend/init_db.py", line 96, in <module>
    init_db()
  File "/Users/edisonlin/Documents/git-repos/軟工專案/backend/init_db.py", line 9, in init_db
    db.drop_all()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 917, in drop_all
    self._call_for_binds(bind_key, "drop_all")
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 881, in _call_for_binds
    getattr(metadata, op_name)(bind=engine)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5896, in drop_all
    bind._run_ddl_visitor(
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3252, in _run_ddl_visitor
    with self.begin() as conn:
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3242, in begin
    with self.connect() as conn:
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3278, in connect
    return self._connection_cls(self)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2442, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3302, in raw_connection
    return self.pool.connect()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 621, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/pymysql/connections.py", line 979, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/pymysql/_auth.py", line 241, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/edisonlin/anaconda3/envs/NTNU_SE_env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1049, "Unknown database 'sys'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
